name: coverage
on:
    pull_request:
        paths-ignore:
            - 'docs/**'
            - 'example/**'
        branches:
            - master
jobs:
    coverage:
        name: Collecting coverage
        runs-on: ubuntu-latest
        env:
            CI_JOB_NUMBER: 1
        steps:
            - uses: actions/checkout@v1
            - uses: artiomtr/jest-coverage-report-action@v2.0-rc.4
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  test-script: npm run test:coverage
                  annotations: none
